# Generated by Django 5.0.1 on 2024-02-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionHl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsHl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeHl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TacheHlive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField()),
                ('action', models.CharField(choices=[('creer', 'CREER'), ('a_creer', 'A_CREER')], default='a_creer', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hight_live.clienthl')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hight_live.competitionhl')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hight_live.teamshl')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hight_live.typehl')),
            ],
        ),
    ]
