# Generated by Django 5.0.1 on 2024-02-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('competition', models.CharField(max_length=255)),
                ('evenement', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField()),
                ('action', models.CharField(choices=[('creer', 'CREER'), ('a_creer', 'A_CREER')], default='a_creer', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
